{
    "plugins": [
        "@semantic-release/github",
        "@semantic-release/release-notes-generator", 
        "@semantic-release/commit-analyzer",
        ["@semantic-release/changelog", {
            "changelogFile": "Assets/Mirage/Runtime/Sockets/FacepunchSteam/CHANGELOG.md",
        }],
        ["@semantic-release/npm", {
            "npmPublish": false,
            "pkgRoot": "Assets/Mirage/Runtime/Sockets/FacepunchSteam"
        }],
        ["@semantic-release/git", {
            "assets": ["Assets/Mirage/Runtime/Sockets/FacepunchSteam/package.json", "Assets/Mirage/Runtime/Sockets/FacepunchSteam/CHANGELOG.md"],
            "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }],
    ]
}
